name: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
      shell: bash
      env:
        SKIP_COMPILE: true
